name: cea
channels:
- omnia
- pythonocc
- dlr-sc
- oce
- conda-forge
- defaults
dependencies:
- backports_abc=0.5=py27_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py27_0
- click=6.7=py27_0
- click-plugins=1.0.3=py27_0
- cligj=0.4.0=py27_0
- curl>=7.49.1
- cycler=0.10.0=py27_0
- descartes=1.1.0=py27_0
- enum34=1.1.6=py27_1
- ephem=3.7.6.0=py27_1
- expat
- fiona>=1.7.8
- freetype=2.7
- freexl=1.0.2
- functools32=3.2.3.2=py27_1
- gdal
- geopandas
- geos>=3.5.1
- hdf4=4.2.12
- hdf5>=1.8.18
- icu=58.1
- jpeg=9b
- kealib>=1.4.7
- krb5=1.14.2
- libgdal>=2.1.0
- libiconv=1.14
- libnetcdf>=4.4.1.1
- libpng
- libpq=9.6.3
- libspatialindex=1.8.5
- libspatialite>=4.3.0a
- libtiff
- libxml2=2.9.4
- matplotlib
- munch>=2.2.0
- openjpeg=2.1.2
- openssl=1.0.2l
- pandas
- pbr=3.1.1=py27_0
- pip>=9.0.0
- proj4=4.9.3
- psycopg2=2.7.1=py27_0
- pyparsing=2.2.0=py27_0
- pyproj=1.9.5.1=py27_0
- pyqt=5.6*
- pysal
- pyscaffold=2.5.6=py27_1
- python=2.7*
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- qt=5.6*
- rtree=0.8.3=py27_0
- setuptools=36.2.2=py27_0
- setuptools_scm=1.15.6=py27_0
- shapely>=1.5.17
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_1
- six=1.10.0=py27_1
- sqlalchemy=1.1.11=py27_0
- sqlite
- ssl_match_hostname=3.5.0.1=py27_1
- tbb=2017_20170226
- tornado=4.5.1=py27_0
- wheel=0.29.0=py27_0
- xerces-c>=3.1.4
- xz=5.2.2=0
- zlib>=1.2.11
- mkl=2017.0.3=0
- mkl-service
- numpy=1.13.1=py27_0
- scikit-learn>=0.18.2
- scipy>=0.19.1
- freeimageplus=3.17.0
- gl2ps=1.3.8
- oce
- cvxopt=1.1.8=py27_0
- pythonocc-core=0.18
- smesh
- pip:
  - alabaster==0.7.10
  - astral==1.4
  - babel==2.4.0
  - backports-abc==0.5
  - backports.ssl-match-hostname==3.5.0.1
  - chardet==3.0.4
  - cloudpickle==0.3.1
  - colorama==0.3.9
  - configparser==3.5.0
  - deap>=1.0.1
  - decorator==4.1.2
  - docutils==0.14
  - doit==0.29.0
  - idna==2.5
  - imagesize==0.7.1
  - ipython-genutils==0.2.0
  - jinja2==2.9.6
  - jsonschema==2.6.0
  - jupyter-core==4.3.0
  - lxml==3.8.0
  - markupsafe==1.0
  - mock
  - nbformat==4.3.0
  - networkx==1.11
  - pkginfo==1.4.1
  - plotly==2.0.7
  - pycollada
  - pygments==2.2.0
  - pyliburo==0.1a12
  - pymc3
  - pymf==0.1.9
  - pyshp==1.2.11
  - requests==2.18.3
  - requests-toolbelt==0.8.0
  - salib==1.0.3
  - seaborn
  - setuptools-scm==1.15.6
  - simpledbf==0.2.6
  - snowballstemmer==1.2.1
  - sphinx==1.6.3
  - sphinxcontrib-websupport==1.0.1
  - timezonefinder==2.1.0
  - tqdm==4.15.0
  - traitlets==4.3.2
  - twine==1.9.1
  - typing==3.6.2
  - urllib3==1.22
  - xlrd==1.0.0
  - xlwt==1.2.0

