name: cea-3.5.0c0
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=19.3.0
  - backcall=0.2.0
  - beautifulsoup4=4.9.1
  - bleach=3.1.5
  - blosc=1.19.0
  - boost-cpp=1.72.0
  - branca=0.4.1
  - brotlipy=0.7.0
  - bs4=4.9.1
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.0
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - colorama=0.4.3
  - cryptography=2.9.2
  - curl=7.69.1
  - cvxopt=1.2.5
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - double-conversion=3.1.5
  - dsdp=5.8
  - eigen=3.3.7
  - entrypoints=0.3
  - esda=2.2.1
  - expat=2.2.9
  - fastcache=1.1.0
  - ffmpeg=4.2.3
  - fftw=3.3.8
  - fiona=1.8.13
  - folium=0.11.0
  - fontconfig=2.13.1
  - freeimage=3.18.0
  - freetype=2.10.2
  - freexl=1.0.5
  - gdal=3.0.4
  - geopandas=0.7.0
  - geos=3.8.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - gevent=20.6.2
  - gevent-websocket=0.10.1
  - giddy=2.3.3
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.64.3
  - glpk=4.65
  - greenlet=0.4.16
  - gsl=2.6
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icc_rt=2019.0.0
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - inequality=1.0.0
  - intel-openmp=2020.0
  - ipdb=0.13.0
  - ipykernel=5.3.2
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9d
  - jsoncpp=1.8.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.5
  - jupyter_core=4.6.3
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libffi=3.2.1
  - libgdal=3.0.4
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libogg=1.3.2
  - libpng=1.6.37
  - libpq=12.2
  - libpysal=4.3.0
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtheora=1.1.1
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvmlite=0.33.0
  - loguru=0.5.0
  - lz4-c=1.9.2
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mapclassify=2.3.0
  - markupsafe=1.1.1
  - matplotlib-base=3.2.1
  - mgwr=2.1.1
  - mistune=0.8.4
  - mkl=2020.0
  - mock=4.0.2
  - mpmath=1.1.0
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - networkx=2.4
  - nose=1.3.7
  - notebook=6.0.3
  - numba=0.50.1
  - numexpr=2.7.1
  - numpy=1.18.5
  - occt=7.4.0
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - osmnx=0.14.1
  - packaging=20.4
  - pandas=1.0.4
  - pandoc=2.10
  - pandocfilters=1.4.2
  - parso=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - pickleshare=0.7.5
  - pip=20.1.1
  - pointpats=2.1.0
  - poppler=0.87.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=7.0.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - pugixml=1.10
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyrsistent=0.16.0
  - pysal=2.2.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.8.3
  - python-dateutil=2.8.0
  - python_abi=3.8
  - pythonocc-core=7.4.0
  - pytz=2020.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=19.0.1
  - quantecon=0.4.7
  - rasterio=1.1.5
  - rasterstats=0.14.0
  - requests=2.23.0
  - rtree=0.9.4
  - scikit-learn=0.23.1
  - scipy=1.3.2
  - seaborn=0.10.1
  - seaborn-base=0.10.1
  - segregation=1.3.0
  - send2trash=1.5.0
  - setuptools=47.1.1
  - shapely=1.7.0
  - simplejson=3.17.0
  - six=1.15.0
  - snuggs=1.4.7
  - soupsieve=2.0.1
  - spaghetti=1.5.0
  - spglm=1.0.7
  - spint=1.0.6
  - splot=1.1.3
  - spreg=1.1.1
  - spvcm=0.3.0
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - sympy=1.6.1
  - tbb=2020.1
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tiledb=1.7.7
  - tk=8.6.10
  - tobler=0.3.1
  - tornado=6.0.4
  - tqdm=4.47.0
  - traitlets=4.3.3
  - urllib3=1.24.3
  - utfcpp=3.1.1
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - vtk=9.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win32_setctime=1.0.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wntr=0.2.2.1
  - xerces-c=3.2.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zope.event=4.4
  - zope.interface=5.1.0
  - zstd=1.4.4
prefix: C:\Users\daren-thomas\AppData\Local\Continuum\miniconda3\envs\cea-3.5.0b8
