name: cea
channels:
- conda-forge
- defaults
dependencies:
- deap
- ephem
- flask
- flask-cors
- flask-restx
- werkzeug==2.0.*
- gevent
- gevent-websocket
- ipykernel
- ipython
- notebook
- openpyxl
- plotly
- sphinx
- sympy
- utm
- wntr=0.2.2.1
- blosc <=1.21.0
- fiona
- geopandas<0.14
- matplotlib-base
- networkx<3
- numba
- numpy<1.24
- numpy-financial
- osmnx<1.4
- pandas<2
- pip
- psutil
- pysal=2.1.0
- python>=3.7
- pythonocc-core=7.4.1
- pytz
- pvlib-python
- scikit-learn=1.3.2
- scipy
- setuptools
- shapely<2
- pyyaml
- timezonefinder
- python-cufflinks
- pip:
  - xlrd
  - xlwt
  - staticmap
  - py4design-cea
  - pyarrow
