name: cea-3.5.0b5
channels:
  - conda-forge
  - dlr-sc
  - pythonocc
  - oce
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - attrs=19.3.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.9.1=py38h32f6830_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - blosc=1.19.0=ha925a31_0
  - boost-cpp=1.72.0=h2ba7cf6_1
  - branca=0.4.1=py_0
  - brotlipy=0.7.0=py38h1e8a9f7_1000
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.0=py38ha419a9e_0
  - cfitsio=3.470=he774522_5
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - colorama=0.4.3=py_0
  - cryptography=2.9.2=py38hba49e27_0
  - curl=7.69.1=h1dcc11c_0
  - cvxopt=1.2.5=py38h9172991_1
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - double-conversion=3.1.5=h6538335_2
  - dsdp=5.8=h6a76313_1203
  - eigen=3.3.7=he980bc4_1001
  - entrypoints=0.3=py38h32f6830_1001
  - esda=2.2.1=py_0
  - expat=2.2.9=he025d50_2
  - fastcache=1.1.0=py38h9de7a3e_1
  - ffmpeg=4.2.3=ha925a31_0
  - fftw=3.3.8=nompi_hbc43ac9_1110
  - fiona=1.8.13=py38h41bf4fa_1
  - folium=0.11.0=py_0
  - fontconfig=2.13.1=hb964e45_1001
  - freeimage=3.18.0=h33f27b4_0
  - freetype=2.10.2=hd328e21_0
  - freexl=1.0.5=hd288d7e_1002
  - gdal=3.0.4=py38h3ba59e7_9
  - geopandas=0.7.0=py_1
  - geos=3.8.1=he025d50_0
  - geotiff=1.5.1=h3d29ae3_10
  - gettext=0.19.8.1=hb01d8f6_1002
  - gevent-websocket=0.10.1=py_0
  - giddy=2.3.3=py_0
  - gl2ps=1.4.2=h2c487a6_0
  - glew=2.1.0=he025d50_0
  - glib=2.64.3=he4de6d7_0
  - glpk=4.65=h2fa13f4_1002
  - greenlet=0.4.16=py38h1e8a9f7_0
  - gsl=2.6=h86b8168_0
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.6=nompi_ha405e13_100
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.9=py_1
  - importlib-metadata=1.7.0=py38h32f6830_0
  - importlib_metadata=1.7.0=0
  - inequality=1.0.0=py_0
  - intel-openmp=2020.0=166
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.15.1=py_0
  - jpeg=9d=he774522_0
  - jsoncpp=1.8.4=h1ad3211_1002
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.5=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - kealib=1.4.13=h3b59ab9_1
  - kiwisolver=1.2.0=py38heaebd3c_0
  - krb5=1.17.1=hdd46e55_0
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libcurl=7.69.1=h1dcc11c_0
  - libffi=3.2.1=h6538335_1007
  - libgdal=3.0.4=h6f60a84_9
  - libiconv=1.15=hfa6e2cd_1006
  - libkml=1.3.0=h7e985d0_1011
  - liblapack=3.8.0=15_mkl
  - libllvm9=9.0.1=hde8ddfe_1
  - libnetcdf=4.7.4=nompi_h256d12c_104
  - libogg=1.3.2=hfa6e2cd_1002
  - libpng=1.6.37=hfe6a214_1
  - libpq=12.2=hd9aa61d_1
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialindex=1.9.3=he025d50_3
  - libspatialite=4.3.0a=h51df0ed_1038
  - libssh2=1.9.0=h3235a2c_2
  - libtheora=1.1.1=h62dcd97_1003
  - libtiff=4.1.0=h885aae3_6
  - libwebp-base=1.1.0=hfa6e2cd_3
  - libxml2=2.9.10=h5d81f1c_1
  - loguru=0.5.0=py38h32f6830_0
  - lz4-c=1.9.2=h62dcd97_1
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - mapclassify=2.3.0=py_0
  - markupsafe=1.1.1=py38h9de7a3e_1
  - matplotlib-base=3.2.1=py38h1626042_0
  - mgwr=2.1.1=py_0
  - mistune=0.8.4=py38h9de7a3e_1001
  - mkl=2020.0=166
  - mock=4.0.2=py38h32f6830_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.7=py_0
  - networkx=2.4=py_1
  - nose=1.3.7=py38h32f6830_1004
  - notebook=6.0.3=py38h32f6830_1
  - numexpr=2.7.1=py38h7ae7562_1
  - numpy=1.18.5=py38h72c728b_0
  - occt=7.4.0=h823b557_6
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1g=he774522_0
  - osmnx=0.14.1=pyh9f0ad1d_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.4=py38he6e81aa_0
  - pandoc=2.10=0
  - parso=0.7.0=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=h6538335_0
  - pickleshare=0.7.5=py38h32f6830_1001
  - pip=20.1.1=py_1
  - pointpats=2.1.0=py_1
  - poppler=0.87.0=h0cd1227_1
  - poppler-data=0.4.9=1
  - postgresql=12.2=he14cc48_1
  - proj=7.0.0=haa36216_3
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - pugixml=1.10=h6538335_1
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py38h1dd9442_0
  - pyrsistent=0.16.0=py38h9de7a3e_0
  - pysal=2.2.0=py_0
  - pysocks=1.7.1=py38h32f6830_1
  - pytables=3.6.1=py38hd2a2a0e_2
  - python=3.8.3=cpython_h5fd99cc_0
  - python-dateutil=2.8.0=py_0
  - python_abi=3.8=1_cp38
  - pythonocc-core=7.4.0=py38ha02cdc8_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pywinpty=0.5.7=py38_0
  - quantecon=0.4.7=py38_0
  - rasterio=1.1.5=py38h151dc71_0
  - rasterstats=0.14.0=py_0
  - requests=2.23.0=pyh8c360ce_2
  - rtree=0.9.4=py38h7ad75cc_1
  - scikit-learn=0.23.1=py38ha1d60b4_0
  - scipy=1.3.2=py38h582fac2_0
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - send2trash=1.5.0=py_0
  - setuptools=47.1.1=py38h32f6830_0
  - shapely=1.7.0=py38hbf43935_3
  - simplejson=3.17.0=py38h9de7a3e_1
  - six=1.15.0=pyh9f0ad1d_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.0.1=py38h32f6830_0
  - spaghetti=1.5.0=py_0
  - spglm=1.0.7=py_0
  - spint=1.0.6=py_0
  - splot=1.1.3=py_0
  - spreg=1.1.1=py_0
  - spvcm=0.3.0=py_0
  - sqlite=3.30.1=hfa6e2cd_0
  - statsmodels=0.11.1=py38h1e8a9f7_2
  - tbb=2020.1=he980bc4_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tiledb=1.7.7=h0b90766_3
  - tk=8.6.10=hfa6e2cd_0
  - tornado=6.0.4=py38hfa6e2cd_0
  - traitlets=4.3.3=py38h32f6830_1
  - urllib3=1.24.3=py38_0
  - utfcpp=3.1.1=0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - vtk=9.0.0=no_osmesa_py38hc3221c0_100
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py38h32f6830_1
  - win32_setctime=1.0.1=py_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_1003
  - winpty=0.4.3=4
  - xerces-c=3.2.2=h6538335_1004
  - xz=5.2.5=h2fa13f4_0
  - zeromq=4.3.2=h6538335_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zope.event=4.4=pyh9f0ad1d_0
  - zope.interface=5.1.0=py38h9de7a3e_0
  - zstd=1.4.4=h9f78265_3
  - ipython==7.15.0
  - numba
  - pip:
    - alabaster==0.7.12
    - aniso8601==8.0.0
    - arviz==0.8.3
    - babel==2.8.0
    - bs4==0.0.1
    - cftime==1.1.3
    - colorlover==0.3.0
    - cufflinks==0.17.3
    - deap==1.3.1
    - docutils==0.16
    - ephem==3.7.7.1
    - et-xmlfile==1.0.1
    - flask==1.1.2
    - flask-restplus==0.13.0
    - flask-socketio==4.3.0
    - future==0.18.2
    - gevent==20.6.1
    - h5py==2.10.0
    - imagesize==1.2.0
    - ipdb==0.13.2
    - ipykernel==5.3.0
    - itsdangerous==1.1.0
    - jdcal==1.4.1
    - jedi==0.17.0
    - keyring==21.2.1
    - libcst==0.3.6
    - libpysal==4.2.2
    - lxml==4.5.1
    - monkeytype==20.5.0
    - mpmath==1.1.0
    - mypy==0.780
    - mypy-extensions==0.4.3
    - netcdf4==1.5.3
    - openpyxl==3.0.3
    - pandocfilters==1.4.2
    - pillow==7.1.2
    - pipdeptree==1.0.0
    - pkginfo==1.5.0.1
    - plotly==4.8.1
    - psutil==5.7.0
    - py4design-cea==0.30
    - pycollada==0.7.1
    - pymc3==3.8
    - pymf==0.1.9
    - pyqt5==5.15.0
    - pyqt5-sip==12.8.0
    - pyshp==2.1.0
    - python-engineio==3.13.0
    - python-socketio==4.6.0
    - pywin32==228
    - pywin32-ctypes==0.2.0
    - pyyaml==5.3.1
    - pyzmq==19.0.1
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - readme-renderer==26.0
    - requests-toolbelt==0.9.1
    - retrying==1.3.3
    - salib==1.3.11
    - segregation==1.2.0
    - snowballstemmer==2.0.0
    - sphinx==3.1.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - staticmap==0.5.4
    - sympy==1.6
    - terminado==0.8.3
    - theano==1.0.4
    - timezonefinder==4.4.0
    - tobler==0.3.0
    - tqdm==4.46.1
    - twine==3.1.1
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.2
    - typing-inspect==0.6.0
    - utm==0.5.0
    - wcwidth==0.2.4
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - wntr==0.1.7
    - xarray==0.15.1
    - xlrd==1.2.0
    - xlwt==1.3.0
prefix: C:\Users\darthoma\Miniconda2\envs\cea-3.5.0b2
