name: cea
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - dlr-sc
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - asn1crypto=0.24.0=py27_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29=py27_0
  - cffi=1.11.5=py27he75722e_1
  - chardet=3.0.4=py27_1
  - conda=4.5.12=py27_0
  - conda-env=2.6.0=1
  - cryptography=2.4.2=py27h1ba5d50_0
  - enum34=1.1.6=py27_1
  - futures=3.2.0=py27_0
  - idna=2.8=py27_0
  - ipaddress=1.0.22=py27_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl-service
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1a=h7b6447c_0
  - pip=18.1=py27_0
  - pycosat=0.6.3=py27h14c3975_0
  - pycparser=2.19=py27_0
  - pyopenssl=18.0.0=py27_0
  - pysocks=1.6.8=py27_0
  - python=2.7.15=h9bab390_6
  - readline=7.0=h7b6447c_5
  - requests=2.21.0=py27_0
  - ruamel_yaml=0.15.46=py27h14c3975_0
  - setuptools=40.6.3=py27_0
  - six=1.12.0=py27_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - urllib3=1.24.1=py27_0
  - wheel=0.32.3=py27_0
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
- pip:
    - alabaster==0.7.12
    - babel==2.6.0
    - backports.shutil-get-terminal-size==1.0.0
    - backports.shutil-which==3.5.2
    - bleach==3.1.0
    - chardet==3.0.4
    - cityenergyanalyst==2.9.0
    - cloudpickle==0.6.1
    - colorama==0.4.1
    - configparser==3.5.0
    - cvxopt==1.2.2
    - dash==0.35.2
    - dash-core-components==0.42.1
    - dash-html-components==0.13.5
    - dash-renderer==0.16.2
    - decorator==4.3.0
    - defusedxml==0.5.0
    - docutils==0.14
    - doit==0.29.0
    - entrypoints==0.3
    - flask==1.0.2
    - flask-compress==1.4.0
    - idna==2.8
    - imagesize==1.1.0
    - ipaddress==1.0.22
    - ipykernel==4.10.0
    - ipython==5.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - itsdangerous==1.1.0
    - jinja2==2.10
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==5.2.0
    - jupyter-core==4.4.0
    - lxml==4.3.0
    - mistune==0.8.4
    - nbconvert==5.4.0
    - nbformat==4.4.0
    - networkx==2.2
    - notebook==5.7.4
    - packaging==18.0
    - pandocfilters==1.4.2
    - pathlib2==2.3.3
    - pickleshare==0.7.5
    - pkginfo==1.5.0.1
    - plotly==2.5.0
    - prometheus-client==0.5.0
    - prompt-toolkit==1.0.15
    - py4design==0.25
    - pycollada==0.6
    - pygments==2.3.1
    - pymf==0.1.9
    - pyshp==2.0.1
    - pywinpty==0.5.5
    - pyyaml==3.13
    - pyzmq==17.1.2
    - qtconsole==4.4.3
    - readme-renderer==24.0
    - requests==2.21.0
    - requests-toolbelt==0.8.0
    - retrying==1.3.3
    - salib==1.2
    - scandir==1.9.0
    - scikit-learn==0.20.2
    - seaborn==0.9.0
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - snowballstemmer==1.2.1
    - sphinx==1.8.3
    - sphinxcontrib-websupport==1.1.0
    - terminado==0.8.1
    - testpath==0.4.2
    - traitlets==4.3.2
    - twine==1.12.1
    - typing==3.6.6
    - urllib3==1.24.1
    - utm==0.4.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.14.1
    - widgetsnbextension==3.4.2
    - win-unicode-console==0.5
    - xlrd==1.2.0
    - xlwt==1.3.0



