name: cityenergyanalyst_docs
channels:
- defaults
dependencies:
- fiona
- geopandas
- mock
- mkl-service
- numpy
- pandas
- pyaml
- python=2.7
- pillow
- sphinx
- sphinx_rtd_theme
- pip:
  - py4design
  - flask
  - flask-wtf
